import React from 'react'
import Certifications from '../../components/Certifications/Certifications'

const Certificate = () => {
  return (
    <div><Certifications/></div>
  )
}

export default Certificate                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    